Add VSCode setup step

diff --git a/sf-bootstrap b/sf-bootstrap
--- a/sf-bootstrap
+++ b/sf-bootstrap
@@ -229,3 +229,27 @@ if [ ! -d validation_scripts ]; then
 else
     printf "\e[1;32m\u2BC5\e[0m Validation scripts directory already exists. Skipping.\n"
 fi
+
+printf "\e[1;34m-----\n\u279C Setting up VSCode environment\n-----\e[0m\n"
+
+vscode=true
+[ "$(command -v code)" ] || { printf "\e[1;33m\u0021\e[0m VSCode not found, skipping\n" && vscode=false; }
+
+if $vscode; then
+    [ -d .vscode ] || mkdir .vscode
+    cp "$bootstrap_tmp_dir"/.vscode/extensions.json .vscode
+    missing_extensions=$(jq .recommendations[] .vscode/extensions.json | sed 's/"//g' | grep --fixed-strings --line-regexp --invert-match --file <(code --list-extensions) --)
+    if [ -z "$missing_extensions" ]; then
+        printf "\e[1;32m\u2713\e[0m All recommended VSCode extensions are installed.\n"
+    else
+        printf "\e[1;33m\u2BC5\e[0m Installing missing VSCode extensions...\n"
+        echo "$missing_extensions" | xargs --max-lines=1 code --install-extension
+    fi
+
+    if [ ! -f .vscode/settings.json ] || $new_project || cmp -s .vscode/settings.json "$bootstrap_tmp_dir"/"$default_files_dir"/settings.json; then
+        printf "\e[1;33m\u2BC5\e[0m Customized .vscode/settings.json file found. Not overwriting.\n"
+    else
+        cp "$bootstrap_tmp_dir"/.vscode/settings.json .vscode
+        printf "\e[1;32m\u2713\e[0m VSCode recommended settings written to local file\n"
+    fi
+fi
