Add more steps

diff --git a/sf-bootstrap b/sf-bootstrap
--- a/sf-bootstrap
+++ b/sf-bootstrap
@@ -5,9 +5,16 @@ pmd_file="pmd-dist-$pmd_version-bin.zip"
 pmd_dir="pmd-bin-$pmd_version"
 pmd_attentis_ruleset_url="https://raw.githubusercontent.com/Attentis-Consulting-Inc/pmd/main/ruleset.xml"
 
-[ "$(command -v sf)" ] || { echo "Cannot find command sf. Is the sf cli installed?" >&2 && exit 1; }
-[ "$(command -v npm)" ] || { echo "Cannot find command npm. Is it installed?" >&2 && exit 1; }
+# Guard for required commands and files
 [ -f sfdx-project.json ] || { echo "Must be run from the root of an sfdx project" >&2 && exit 1; }
+valid_reqs=true
+[ "$(command -v npm)" ] || { echo "Cannot find command npm. Is it installed?" >&2 && valid_reqs=false; }
+[ "$(command -v jq)" ] || { echo "Cannot find command jq. Is it installed?" >&2 && valid_reqs=false; }
+[ "$(command -v sf)" ] || { echo "Cannot find command sf. Is the sf cli installed?" >&2 && valid_reqs=false; }
+
+[ $valid_reqs = true ] || { echo "" && echo "Some prerequisites not met. Please follow the setup instructions on the repository" >&2 && exit 1; }
+
+npm_installed_packages=$(npm ls -i)
 
 printf "\e[1;34m-----\n\u279C Setting up repository\n-----\e[0m\n"
 
@@ -20,7 +27,7 @@ fi
 if [ -f .gitignore-local ]; then
     printf "\e[1;33m\u2BC5\e[0m Found a local git ignore file\n"
 else
-    ln -sf .git/info/exclude .gitignore-local
+    ln -s .git/info/exclude .gitignore-local
     echo ".gitignore-local" >.gitignore-local
     printf "\e[1;32m\u2713\e[0m Created .gitignore-local file.\n"
     printf "\e[1;33m\u0021\e[0m You can use this file to ignore files in git without committing changes to .gitignore\n"
@@ -36,17 +43,23 @@ elif [ "$(command -v rg)" ]; then
     printf "\e[1;33m\u0021\e[0m You can use this file to ignore files when using ripgrep\n"
 fi
 
+if [ -f omnistudio-components.json ]; then
+    printf "\e[1;33m\u2BC5\e[0m Found omnistudio-components.json file\n"
+else
+    jq '[.packageDirectories[].path] | map ( { (.):[] } ) | add' sfdx-project.json >omnistudio-components.json
+    printf "\e[1;32m\u2713\e[0m Created omnistudio-components.json file\n"
+    printf "\e[1;33m\u0021\e[0m You can use this file to list omnistudio lwcs in each project package, so they can be excluded from certain validations\n"
+fi
+
 printf "\e[1;34m-----\n\u279C Installing Prettier\n-----\e[0m\n"
 prettier_installed=false
-if [ -n "$(npm ls -p prettier)" ] && [ -n "$(npm ls -p prettier-plugin-apex)" ]; then
-    printf "\e[1;32m\u2713\e[0m Prettier and Apex plugin already installed\n"
-    prettier_installed=true
-else
+(echo "$npm_installed_packages" | grep "prettier@" >/dev/null 2>&1) && (echo "$npm_installed_packages" | grep "prettier-plugin-apex@" >/dev/null 2>&1) && printf "\e[1;32m\u2713\e[0m Prettier and Apex plugin already installed\n" && prettier_installed=true
+if [ $prettier_installed = false ]; then
     {
-        npm install prettier prettier-plugin-apex &&
+        npm install -D prettier prettier-plugin-apex &&
             printf "\n\e[1;32m\u2713\e[0m Prettier and Apex plugin installed\n" &&
             prettier_installed=true
-    } || printf "\n\e[1;31m\u274C\e[0m Failed to install Prettier and Apex plugin\n"
+    } || printf "\n\e[1;31m\u274C\e[0m Failed to install Prettier and Apex plugin. Check errors and try again to complete Prettier setup\n"
 fi
 
 if [ $prettier_installed ]; then
@@ -79,35 +92,61 @@ if [ $prettier_installed ]; then
         mv -- "$temp_prettierrc" .prettierrc
         printf "\e[1;32m\u2713\e[0m Set up printWidth of 120 for Apex\n"
     fi
+
+    printf "\n\e[1;32m\u2713\e[0m .prettierrc set up for Apex rules\n"
 fi
 
 printf "\e[1;34m-----\n\u279C Setting up PMD\n-----\e[0m\n"
 
 mkdir -p pmd/rulesets
-install_pmd=true
-if [ "$(command -v pmd)" ]; then
+install_pmd=false
+[ -f pmd/bin/pmd ] || install_pmd=true
+if [ "$(command -v pmd)" ] && [ $install_pmd = true ]; then
     read -r -p "Found global pmd command, set up local binary anyways? (y/N): " yn
     [[ "$yn" == [Yy]* ]] || install_pmd=false
 fi
 
 if [ $install_pmd ]; then
     printf "\e[1;33m\u2BC5\e[0m Downloading PMD v%s\n" $pmd_version
-    wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F"$pmd_version"/"$pmd_file" --no-verbose
-    { [ -f "$pmd_file" ] && unzip "$pmd_file" -q && mv "$pmd_dir" pmd; } || echo "Failed to download pmd" >&2
+    curl -LO https://github.com/pmd/pmd/releases/download/pmd_releases%2F"$pmd_version"/"$pmd_file" --no-verbose || echo "Failed to download pmd. Check errors and try again to complete PMD setup." >&2
+    [ -f "$pmd_file" ] && unzip "$pmd_file" -q && mv "$pmd_dir" pmd && rm -f "$pmd_file" && printf "\n\e[1;32m\u2713\e[0m Local PMD binary set up\n"
+else
+    printf "\e[1;32m\u2713\e[0m PMD binary already exists\n"
 fi
 
-download_ruleset=true
-if [ -f "$HOME"/.config/pmd/rulesets/apex.xml ]; then
-    read -r -p "Found global Apex PMD ruleset. Copy that one? (y/N): " yn
+download_ruleset=false
+[ -f pmd/rulesets/apex.xml ] || download_ruleset=true
+if [ -f "$HOME"/.config/pmd/rulesets/apex.xml ] && [ $download_ruleset = true ]; then
+    read -r -p "Found global Apex PMD ruleset. Copy that one instead of downloading? (y/N): " yn
     if [[ "$yn" == [Yy]* ]]; then
         cp "$HOME"/.config/pmd/rulesets/apex.xml pmd/rulesets/
         download_ruleset=false
     fi
 fi
+
 if [ $download_ruleset ]; then
     printf "\e[1;33m\u2BC5\e[0m Downloading Attentis ruleset\n"
-    wget "$pmd_attentis_ruleset_url" -O pmd/rulesets/apex.xml --no-verbose || echo "Failed to download ruleset" >&2
+    curl -L "$pmd_attentis_ruleset_url" -o pmd/rulesets/apex.xml --no-verbose || echo "Failed to download ruleset. Check errors and try again to complete ruleset setup." >&2
+else
+    printf "\e[1;32m\u2713\e[0m Apex ruleset for PMD already exists\n"
 fi
 
 printf "\e[1;34m-----\n\u279C Setting up ESLint and Jest\n-----\e[0m\n"
-sf force lightning lwc test setup && printf "\n\e[1;32m\u2713\e[0m ESLint and Jest set up\n"
+setup_lwc=false
+{ (echo "$npm_installed_packages" | grep "eslint@" >/dev/null 2>&1) && (echo "$npm_installed_packages" | grep "@lwc/eslint-plugin-lwc@" >/dev/null 2>&1) && (echo "$npm_installed_packages" | grep "@salesforce/eslint-config-lwc@" >/dev/null 2>&1) && (echo "$npm_installed_packages" | grep "@salesforce/eslint-plugin-aura@" >/dev/null 2>&1) && (echo "$npm_installed_packages" | grep "@salesforce/eslint-plugin-lightning@" >/dev/null 2>&1) && (echo "$npm_installed_packages" | grep "@salesforce/sfdx-lwc-jest" >/dev/null 2>&1); } || setup_lwc=true
+
+if [ $setup_lwc = true ]; then
+    sf force lightning lwc test setup && printf "\n\e[1;32m\u2713\e[0m ESLint and Jest set up\n"
+else
+    printf "\e[1;32m\u2713\e[0m All required ESLint and Jest packages already exist\n"
+fi
+
+printf "\e[1;34m-----\n\u279C Setting up sa11y\n-----\e[0m\n"
+setup_sa11y=false
+(echo "$npm_installed_packages" | grep "@sa11y/jest@" >/dev/null 2>&1) || setup_sa11y=true
+
+if [ $setup_sa11y = true ]; then
+    npm install -D @sa11y/jest || printf "\n\e[1;31m\u274C\e[0m Failed to install @sa11y/jest. Check errors and try again.\n"
+else
+    printf "\e[1;32m\u2713\e[0m sa11y/jest already installed.\n"
+fi
