Fix error messages

diff --git a/sf-bootstrap b/sf-bootstrap
--- a/sf-bootstrap
+++ b/sf-bootstrap
@@ -36,7 +36,7 @@ if [ ! -f sfdx-project.json ]; then
 fi
 
 printf "\e[1;34m-----\n\u279C Gathering bootstrap files\n-----\e[0m\n"
-curl -JL "$bootstrap_url" -o "$bootstrap_tmp_file" || { echo "Failed to download bootstrap files. Check errors and try again" >&2 && exit 1; }
+curl -JL "$bootstrap_url" -o "$bootstrap_tmp_file" || { printf "\n\e[1;31m\u274C\e[0m Failed to download bootstrap files. Check errors and try again\n" >&2 && exit 1; }
 unzip -q "$bootstrap_tmp_file" -d /tmp
 trap "rm -rf $bootstrap_tmp_dir $bootstrap_tmp_file" EXIT
 
@@ -146,7 +146,7 @@ packages_to_install=
 (echo "$npm_installed_packages" | grep "canvas@" >/dev/null 2>&1) || packages_to_install+="canvas "
 
 if [ -n "$packages_to_install" ]; then
-    { echo "$packages_to_install" | xargs npm install -D && printf "\n\e[1;32m\u2713\e[0m sa11y/jest and canvas installed.\n"; } || printf "\n\e[1;31m\u274C\e[0m Failed to install @sa11y/jest or canvas. Check errors and try again.\n"
+    { echo "$packages_to_install" | xargs npm install -D && printf "\n\e[1;32m\u2713\e[0m sa11y/jest and canvas installed.\n"; } || printf "\n\e[1;31m\u274C\e[0m Failed to install @sa11y/jest or canvas. Check errors and try again.\n" >&2
 else
     printf "\e[1;32m\u2713\e[0m sa11y/jest and canvas already installed.\n"
 fi
@@ -154,14 +154,14 @@ fi
 mkdir -p jest/setupFiles
 
 if [ -f jest/setupFiles/sa11y-setup.js ]; then
-    printf "\e[1;32m\u2BC5\e[0m sa11y setup file already exists. Not overwriting.\n"
+    printf "\e[1;33m\u2BC5\e[0m sa11y setup file already exists. Not overwriting.\n"
 else
     cp "$bootstrap_tmp_dir"/jest/setupFiles/sa11y-setup.js jest/setupFiles
     printf "\e[1;32m\u2713\e[0m Created jest/setupFiles/sa11y-setup.js. Make sure it is called from jest.config.js\n"
 fi
 
 if [ -f jest/setupFiles/setEnvVars.js ]; then
-    printf "\e[1;32m\u2BC5\e[0m setEnvVars.js file for jest already exists. Not overwriting.\n"
+    printf "\e[1;33m\u2BC5\e[0m setEnvVars.js file for jest already exists. Not overwriting.\n"
 else
     cp "$bootstrap_tmp_dir"/jest/setupFiles/setEnvVars.js jest/setupFiles
     printf "\e[1;32m\u2713\e[0m Created jest/setupFiles/setEnvVars.js using the extended ruleset. Make sure it is called from jest.config.js\n"
@@ -171,7 +171,7 @@ write_jestconfig=false
 if [ ! -f jest.config.js ] || $new_project || cmp -s jest.config.js "$bootstrap_tmp_dir"/"$default_files_dir"/jest.config.js; then
     write_jestconfig=true
 else
-    printf "\e[1;32m\u2BC5\e[0m Customized Jest config file (jest.config.js) already exists. Not overwriting. Check the bootstrap repository's README on how to add these to your jest.config.js file, if needed.\n"
+    printf "\e[1;33m\u2BC5\e[0m Customized Jest config file (jest.config.js) already exists. Not overwriting. Check the bootstrap repository's README on how to add these to your jest.config.js file, if needed.\n"
 fi
 
 if $write_jestconfig; then
@@ -182,9 +182,13 @@ fi
 printf "\n\e[1;34m-----\n\u279C Setting up PMD\n-----\e[0m\n"
 
 if [ ! -f pmd/bin/pmd ]; then
-    printf "\e[1;33m\u2BC5\e[0m Downloading PMD v%s\n" $pmd_version
-    curl -LO https://github.com/pmd/pmd/releases/download/pmd_releases%2F"$pmd_version"/"$pmd_file" || echo "Failed to download pmd. Check errors and try again to complete PMD setup." >&2
-    [ -f "$pmd_file" ] && unzip -q "$pmd_file" && mv "$pmd_dir" pmd && rm -f "$pmd_file" && printf "\n\e[1;32m\u2713\e[0m Local PMD binary set up\n"
+    if [ ! -d pmd ]; then
+        printf "\e[1;33m\u2BC5\e[0m Downloading PMD v%s\n" $pmd_version
+        curl -LO https://github.com/pmd/pmd/releases/download/pmd_releases%2F"$pmd_version"/"$pmd_file" || printf "\n\e[1;31m\u274C\e[0m Failed to download pmd. Check errors and try again to complete PMD setup.\n" >&2
+        [ -f "$pmd_file" ] && unzip -q "$pmd_file" && mv "$pmd_dir" pmd && rm -f "$pmd_file" && printf "\n\e[1;32m\u2713\e[0m Local PMD binary set up\n"
+    else
+        printf "\e[1;33m\u2BC5\e[0m PMD binary not found, but pmd directory exists. Skipping PMD download.\n"
+    fi
 else
     printf "\e[1;32m\u2713\e[0m PMD binary already exists\n"
 fi
@@ -193,8 +197,8 @@ mkdir -p pmd/rulesets
 
 if [ ! -f pmd/rulesets/apex.xml ]; then
     printf "\e[1;33m\u2BC5\e[0m Downloading PMD ruleset\n"
-    curl -L "$pmd_attentis_ruleset_url" -o pmd/rulesets/apex.xml || echo "Failed to download ruleset. Check errors and try again to complete ruleset setup." >&2
-    printf "\n\e[1;32m\u2713\e[0m Apex ruleset for PMD created\n"
+    curl -L "$pmd_attentis_ruleset_url" -o pmd/rulesets/apex.xml || printf "\n\e[1;31m\u274C\e[0m Failed to download ruleset. Check errors and try again to complete ruleset setup.\n" >&2
+    [ -f pmd/rulesets/apex.xml ] && printf "\n\e[1;32m\u2713\e[0m Apex ruleset for PMD created\n"
 else
     printf "\e[1;32m\u2713\e[0m Apex ruleset for PMD already exists\n"
 fi
@@ -203,14 +207,16 @@ printf "\n\e[1;34m-----\n\u279C Setting up validation scripts\n-----\e[0m\n"
 if [ ! -d validation_scripts ]; then
     printf "\e[1;33m\u2BC5\e[0m Downloading latest version of validation scripts\n"
     downloaded_scripts=true
-    curl -LO "$validations_url"/releases/latest/download/validation_scripts.zip || { echo "Failed to download validation scripts. Check errors and try again to complete setup." >&2 && downloaded_scripts=false; }
+    curl -LO "$validations_url"/releases/latest/download/validation_scripts.zip || {
+        printf "\n\e[1;31m\u274C\e[0m Failed to download validation scripts. Check errors and try again to complete setup.\n" >&2 && downloaded_scripts=false
+    }
     if $downloaded_scripts; then
         unzip -q "$validations_filename" -d validation_scripts
         rm -f "$validations_filename"
         printf "\n\e[1;32m\u2713\e[0m Validation scripts installed\n"
     fi
 else
-    printf "\e[1;32m\u2BC5\e[0m Validation scripts directory already exists. Skipping.\n"
+    printf "\e[1;33m\u2BC5\e[0m Validation scripts directory already exists. Skipping.\n"
 fi
 
 printf "\n\e[1;34m-----\n\u279C Setting up VSCode environment\n-----\e[0m\n"
