Download bootstrap files once and copy

diff --git a/sf-bootstrap b/sf-bootstrap
--- a/sf-bootstrap
+++ b/sf-bootstrap
@@ -1,12 +1,17 @@
 #!/bin/bash
 
-bootstrap_url=https://github.com/Attentis-Consulting-Inc/sfdx-bootstrap/main
+bootstrap_url=https://github.com/Attentis-Consulting-Inc/sfdx-bootstrap/archive/main.zip
+bootstrap_tmp_file=tmp/sfdx-bootstrap.zip
+bootstrap_tmp_dir=tmp/sfdx-bootstrap
+default_files_dir=.default_sfdx_files
+
 validations_url=https://github.com/Attentis-Consulting-Inc/validation-scripts/main
 validations_filename=validation_scripts.zip
+
 pmd_version="7.0.0"
 pmd_file="pmd-dist-$pmd_version-bin.zip"
 pmd_dir="pmd-bin-$pmd_version"
-pmd_attentis_ruleset_url="https://raw.githubusercontent.com/Attentis-Consulting-Inc/pmd/main/ruleset.xml"
+pmd_attentis_ruleset_url="https://raw.githubusercontent.com/Attentis-Consulting-Inc/pmd/main/apex.xml"
 
 # Guard for required commands and files
 valid_reqs=true
@@ -17,6 +22,7 @@ valid_reqs=true
 [ $valid_reqs = true ] || { echo "" && echo "Some prerequisites not met. Please follow the setup instructions on the repository" >&2 && exit 1; }
 
 # Check if being run on an existing project, or prompt to create new one
+new_project=false
 if [ ! -f sfdx-project.json ]; then
     read -r -p "Not in an SFDX project. Create one here? (Y/n) " project_yn
     [[ "$project_yn" == [Nn]* ]] && exit 0
@@ -26,7 +32,13 @@ if [ ! -f sfdx-project.json ]; then
     done
     sf generate project -n "$project_name" || exit 1
     cd "$project_name" || exit 1
+    new_project=true
 fi
+
+printf "\e[1;34m-----\n\u279C Gathering bootstrap files\n-----\e[0m\n"
+curl -JL "$bootstrap_url" -o "$bootstrap_tmp_file" || { echo "Failed to download bootstrap files. Check errors and try again" >&2 && exit 1; }
+unzip -q "$bootstrap_tmp_file" -d "$bootstrap_tmp_dir"
+trap "rm -rf $bootstrap_tmp_dir $bootstrap_tmp_file" EXIT
 
 printf "\e[1;34m-----\n\u279C Git setup\n-----\e[0m\n"
 
@@ -79,38 +91,44 @@ if [ $prettier_installed = false ]; then
     } || printf "\n\e[1;31m\u274C\e[0m Failed to install Prettier and Apex plugin. Check errors and try again to complete Prettier setup\n"
 fi
 
-if [ $prettier_installed ]; then
-    printf "\e[1;33m\u0021\e[0m Setting up Apex rules for Prettier:\n"
+if $prettier_installed; then
     [ -f .prettierrc ] || echo "{\"trailingComma\": \"none\"}" >.prettierrc
-    if ! jq -e '.overrides[]' .prettierrc &>/dev/null; then
-        temp_prettierrc=$(mktemp)
-        jq '.overrides = []' .prettierrc >"$temp_prettierrc"
-        mv -- "$temp_prettierrc" .prettierrc
+
+    if $new_project || cmp -s .prettierrc "$bootstrap_tmp_dir"/"$default_files_dir"/.prettierrc; then
+        printf "\e[1;33m\u0021\e[0m Overwriting default .prettierrc to include Apex rules\n"
+        cp "$bootstrap_tmp_dir"/.prettierrc .prettierrc
+    else
+        printf "\e[1;33m\u0021\e[0m Adding Apex rules to .prettierrc\n"
+        if ! jq -e '.overrides[]' .prettierrc &>/dev/null; then
+            temp_prettierrc=$(mktemp)
+            jq '.overrides = []' .prettierrc >"$temp_prettierrc"
+            mv -- "$temp_prettierrc" .prettierrc
+        fi
+        if ! jq -e '.overrides[] | select(.files=="*.{cls,trigger}")' .prettierrc &>/dev/null; then
+            temp_prettierrc=$(mktemp)
+            jq '.overrides += [{"files": "*.{cls,trigger}"}]' .prettierrc >"$temp_prettierrc"
+            mv -- "$temp_prettierrc" .prettierrc
+            printf "\t\e[1;32m\u2713\e[0m Created Prettier rules for Apex\n"
+        fi
+        if ! jq -e '.overrides[] | select(.files=="*.{cls,trigger}").options' .prettierrc &>/dev/null; then
+            temp_prettierrc=$(mktemp)
+            jq '.overrides = [.overrides[] | select(.files=="*.{cls,trigger}") += {"options": {}}]' .prettierrc >"$temp_prettierrc"
+            mv -- "$temp_prettierrc" .prettierrc
+        fi
+        if [ ! "$(jq -e '.overrides[] | select(.files=="*.{cls,trigger}").options.tabWidth' .prettierrc 2>/dev/null)" = "4" ]; then
+            temp_prettierrc=$(mktemp)
+            jq '.overrides = [.overrides[] | select(.files=="*.{cls,trigger}").options.tabWidth = 4]' .prettierrc >"$temp_prettierrc"
+            mv -- "$temp_prettierrc" .prettierrc
+            printf "\t\e[1;32m\u2713\e[0m Set up tabWidth of 4 for Apex\n"
+        fi
+        if [ ! "$(jq -e '.overrides[] | select(.files=="*.{cls,trigger}").options.printWidth' .prettierrc 2>/dev/null)" = "120" ]; then
+            temp_prettierrc=$(mktemp)
+            jq '.overrides = [.overrides[] | select(.files=="*.{cls,trigger}").options.printWidth = 120]' .prettierrc >"$temp_prettierrc"
+            mv -- "$temp_prettierrc" .prettierrc
+            printf "\t\e[1;32m\u2713\e[0m Set up printWidth of 120 for Apex\n"
+        fi
+        printf "\t\e[1;32m\u2713\e[0m .prettierrc is set up with Apex rules\n"
     fi
-    if ! jq -e '.overrides[] | select(.files=="*.{cls,trigger}")' .prettierrc &>/dev/null; then
-        temp_prettierrc=$(mktemp)
-        jq '.overrides += [{"files": "*.{cls,trigger}"}]' .prettierrc >"$temp_prettierrc"
-        mv -- "$temp_prettierrc" .prettierrc
-        printf "\t\e[1;32m\u2713\e[0m Created Prettier rules for Apex\n"
-    fi
-    if ! jq -e '.overrides[] | select(.files=="*.{cls,trigger}").options' .prettierrc &>/dev/null; then
-        temp_prettierrc=$(mktemp)
-        jq '.overrides = [.overrides[] | select(.files=="*.{cls,trigger}") += {"options": {}}]' .prettierrc >"$temp_prettierrc"
-        mv -- "$temp_prettierrc" .prettierrc
-    fi
-    if [ ! "$(jq -e '.overrides[] | select(.files=="*.{cls,trigger}").options.tabWidth' .prettierrc 2>/dev/null)" = "4" ]; then
-        temp_prettierrc=$(mktemp)
-        jq '.overrides = [.overrides[] | select(.files=="*.{cls,trigger}").options.tabWidth = 4]' .prettierrc >"$temp_prettierrc"
-        mv -- "$temp_prettierrc" .prettierrc
-        printf "\t\e[1;32m\u2713\e[0m Set up tabWidth of 4 for Apex\n"
-    fi
-    if [ ! "$(jq -e '.overrides[] | select(.files=="*.{cls,trigger}").options.printWidth' .prettierrc 2>/dev/null)" = "120" ]; then
-        temp_prettierrc=$(mktemp)
-        jq '.overrides = [.overrides[] | select(.files=="*.{cls,trigger}").options.printWidth = 120]' .prettierrc >"$temp_prettierrc"
-        mv -- "$temp_prettierrc" .prettierrc
-        printf "\t\e[1;32m\u2713\e[0m Set up printWidth of 120 for Apex\n"
-    fi
-    printf "\t\e[1;32m\u2713\e[0m .prettierrc is set up with Apex rules\n"
 fi
 
 setup_lwc=false
@@ -136,35 +154,29 @@ fi
 mkdir -p jest/setupFiles
 
 if [ -f jest/setupFiles/sa11y-setup.js ]; then
-    printf "\e[1;32m\u2713\e[0m sa11y setup file already exists\n"
+    printf "\e[1;32m\u2BC5\e[0m sa11y setup file already exists. Not overwriting.\n"
 else
-    printf "\e[1;33m\u2BC5\e[0m Downloading sa11y-setup.js\n"
-    curl -L "$bootstrap_url"/jest/setupFiles/sa11y-setup.js -o jest/setupFiles/sa11y-setup.js
+    cp "$bootstrap_tmp_dir"/jest/setupFiles/sa11y-setup.js jest/setupFiles
     printf "\e[1;32m\u2713\e[0m Created jest/setupFiles/sa11y-setup.js. Make sure it is called from jest.config.js\n"
 fi
 
 if [ -f jest/setupFiles/setEnvVars.js ]; then
-    printf "\e[1;32m\u2713\e[0m setEnvVars.js file for jest already exists\n"
+    printf "\e[1;32m\u2BC5\e[0m setEnvVars.js file for jest already exists. Not overwriting.\n"
 else
-    printf "\e[1;33m\u2BC5\e[0m Downloading setEnvVars.js\n"
-    curl -L "$bootstrap_url"/jest/setupFiles/setEnvVars.js -o jest/setupFiles/setEnvVars.js
+    cp "$bootstrap_tmp_dir"/jest/setupFiles/setEnvVars.js jest/setupFiles
     printf "\e[1;32m\u2713\e[0m Created jest/setupFiles/setEnvVars.js using the extended ruleset. Make sure it is called from jest.config.js\n"
 fi
 
 write_jestconfig=false
-if [ -f jest.config.js ]; then
-    echo
-    read -r -p "Jest config file (jest.config.js) already exists. Overwrite it to include the sa11y and omnistudio-components.json configurations? Only do this on a new project, or if you're sure of what you're doing. (y/N) " jest_yn
-    echo
-    [[ "$jest_yn" == [Yy]* ]] && write_jestconfig=true
-else
+if [ ! -f jest.config.js ] || $new_project || cmp -s jest.config.js "$bootstrap_tmp_dir"/"$default_files_dir"/jest.config.js; then
     write_jestconfig=true
+else
+    printf "\e[1;32m\u2BC5\e[0m Customized Jest config file (jest.config.js) already exists. Not overwriting. Check the bootstrap repository's README on how to add these to your jest.config.js file, if needed.\n"
 fi
 
 if $write_jestconfig; then
-    printf "\e[1;33m\u2BC5\e[0m Downloading jest.config.js\n"
-    curl -L "$bootstrap_url"/jest.config.js -o jest.config.js
-    printf "\e[1;32m\u2713\e[0m jest.config.js overwritten\n"
+    cp "$bootstrap_tmp_dir"/jest.config.js jest.config.js
+    printf "\e[1;32m\u2713\e[0m jest.config.js written\n"
 fi
 
 printf "\e[1;34m-----\n\u279C Setting up PMD\n-----\e[0m\n"
@@ -179,7 +191,7 @@ fi
 
 if $install_pmd; then
     printf "\e[1;33m\u2BC5\e[0m Downloading PMD v%s\n" $pmd_version
-    curl -LO https://github.com/pmd/pmd/releases/download/pmd_releases%2F"$pmd_version"/"$pmd_file" --no-verbose || echo "Failed to download pmd. Check errors and try again to complete PMD setup." >&2
+    curl -LO https://github.com/pmd/pmd/releases/download/pmd_releases%2F"$pmd_version"/"$pmd_file" || echo "Failed to download pmd. Check errors and try again to complete PMD setup." >&2
     [ -f "$pmd_file" ] && unzip -q "$pmd_file" && mv "$pmd_dir" pmd && rm -f "$pmd_file" && printf "\n\e[1;32m\u2713\e[0m Local PMD binary set up\n"
 else
     printf "\e[1;32m\u2713\e[0m PMD binary already exists\n"
@@ -199,7 +211,7 @@ fi
 
 if $download_ruleset; then
     printf "\e[1;33m\u2BC5\e[0m Downloading PMD ruleset\n"
-    curl -L "$pmd_attentis_ruleset_url" -o pmd/rulesets/apex.xml --no-verbose || echo "Failed to download ruleset. Check errors and try again to complete ruleset setup." >&2
+    curl -L "$pmd_attentis_ruleset_url" -o pmd/rulesets/apex.xml || echo "Failed to download ruleset. Check errors and try again to complete ruleset setup." >&2
 else
     printf "\e[1;32m\u2713\e[0m Apex ruleset for PMD already exists\n"
 fi
@@ -215,5 +227,5 @@ if [ ! -d validation_scripts ]; then
         printf "\e[1;32m\u2713\e[0m Validation scripts installed\n"
     fi
 else
-    printf "\e[1;32m\u2713\e[0m Validation scripts directory already exists\n"
+    printf "\e[1;32m\u2BC5\e[0m Validation scripts directory already exists. Skipping.\n"
 fi
